
all:
	gfortran -o gram dml_mat.f90 gram.f90
	gfortran -o gaujor dml_mat.f90 gaujor.f90
	gfortran -o jacobi dml_mat.f90 jacobi.f90
	gfortran -o gaussel dml_mat.f90 gaussel.f90

clean:
	rm *mod *out gram gaujor jacobi gaussel
